load "src/utility.maude"
load "src/syntax/sorts.maude"
load "src/syntax/utility.maude"
load "src/typechecking/sorts.maude"
load "src/typechecking/environment.maude"
load "src/typechecking/unification.maude"
load "src/typechecking/builtins.maude"
load "src/typechecking/function_unification.maude"
load "src/typechecking/checker.maude"
load "src/codegen/sorts.maude"
load "src/codegen/generator.maude"

mod ENKI is
    protecting ENKI-CODEGEN .
endm

