#!/usr/bin/env swipl

:- use_module(library(clpfd)).

:- style_check(-singleton).
:- style_check(-no_effect).
:- style_check(-var_branches).
:- style_check(-discontiguous).
:- style_check(-charset).

% FuncType (TypeName [Named "pair",Any "T4",Any "T5"]) (Any "T4")
first(AUTOGENARG2,A) :-
    AUTOGENARG2 = leftcurly__semicolon__rightcurly_(A,B).

% FuncType (TypeName [Named "pair",Any "T13",Any "T14"]) (Any "T14")
second(AUTOGENARG2,B) :-
    AUTOGENARG2 = leftcurly__semicolon__rightcurly_(A,B).

% FuncType (TypeName [Named "pair",EnkiInt,EnkiInt]) (FuncType (TypeName [Named "pair",EnkiInt,EnkiInt]) EnkiInt)
test(AUTOGENARG2,AUTOGENARG3,AUTOGENERATEDFUNCTIONRESULT) :-
    AUTOGENARG2 = leftcurly__semicolon__rightcurly_(A,B),
    AUTOGENARG3 = leftcurly__semicolon__rightcurly_(C,D),
    Temp0 #= (B + 1),
    Temp1 #= (D + 1),
    Temp2 #= (Temp0 * Temp1),
    A = Temp2,
    (
            A #> C
            ->
            AUTOGENERATEDFUNCTIONRESULT = D
        ;
            AUTOGENERATEDFUNCTIONRESULT = C
    ).
