#!/usr/bin/env swipl

:- use_module(library(clpfd)).

:- use_module(library(yall)).

:- style_check(-singleton).
:- style_check(-no_effect).
:- style_check(-var_branches).
:- style_check(-discontiguous).
:- style_check(-charset).


map_built_in(F,empty(), empty()).
map_built_in(F,cons(H,T),cons(NewH,NewT)) :-
    call(F, H, NewH),
    map_built_in(F, T, NewT).

filter_built_in(F, empty(), empty()).
filter_built_in(F, cons(H, T), Out) :-
    call(F, H) ->
        filter_built_in(F, T, Temp),
        Out = cons(H, Temp);
    filter_built_in(F, T, Out).

call_built_in(F, X, Res) :- call(F, X, Res).



:- initialization(main, main).

main(Argv) :-
    f(-1,Temp2),
    display(Temp2),
    f(3,Temp4),
    display(Temp4),
    f(6,Temp6),
    display(Temp6),
    f(10,Temp8),
    display(Temp8),
    f(20,Temp10),
    display(Temp10).
% EnkiString
display(X) :-
    writeln(X).

% FuncType EnkiInt EnkiString
f(X,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            X #> 5
            ->
            (
                    X #> 10
                    ->
                    AUTOGENERATEDFUNCTIONRESULT = "more than 10"
                ;
                (
                        X #> 7
                        ->
                        AUTOGENERATEDFUNCTIONRESULT = "more than 7"
                    ;
                        AUTOGENERATEDFUNCTIONRESULT = "at least 5"
                )
            )
        ;
        (
                X #< 0
                ->
                AUTOGENERATEDFUNCTIONRESULT = "negative"
            ;
                AUTOGENERATEDFUNCTIONRESULT = "blah"
        )
    ).