#!/usr/bin/env swipl

:- use_module(library(clpfd)).

:- style_check(-singleton).
:- style_check(-no_effect).
:- style_check(-var_branches).
:- style_check(-discontiguous).
:- style_check(-charset).

:- initialization(main, main).

main(Argv) :-
    f(-1,Temp0),
    display(Temp0),
    f(3,Temp1),
    display(Temp1),
    f(6,Temp2),
    display(Temp2),
    f(10,Temp3),
    display(Temp3),
    f(20,Temp4),
    display(Temp4).
% EnkiString
display(X) :-
    writeln(X).

% FuncType EnkiInt EnkiString
f(X,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            X #> 5
            ->
            (
                    X #> 10
                    ->
                    AUTOGENERATEDFUNCTIONRESULT = "more than 10"
                ;
                (
                        X #> 7
                        ->
                        AUTOGENERATEDFUNCTIONRESULT = "more than 7"
                    ;
                        AUTOGENERATEDFUNCTIONRESULT = "at least 5"
                )
            )
        ;
        (
                X #< 0
                ->
                AUTOGENERATEDFUNCTIONRESULT = "negative"
            ;
                AUTOGENERATEDFUNCTIONRESULT = "blah"
        )
    ).