#!/usr/bin/env swipl

:- use_module(library(clpfd)).

:- style_check(-singleton).
:- style_check(-no_effect).
:- style_check(-var_branches).
:- style_check(-discontiguous).
:- style_check(-charset).

:- initialization(main, main).

main(Argv) :-
    insert_into(1,2,empty(),Temp102),
    increment_key_in(1,Temp102,Temp103),
    format_list(Temp103,Temp104),
    display(Temp104),
    first_vote_for_in(cons(1,cons(2,empty())),cons(1,empty()),Temp105),
    as_text(Temp105,Temp106),
    display(Temp106),
    tally_votes_for_in(cons(1,cons(2,empty())),cons(cons(1,empty()),empty()),Temp107),
    as_text(Temp107,Temp108),
    display(Temp108),
    tally_votes_for_in(cons(1,cons(2,empty())),cons(cons(1,empty()),cons(cons(1,cons(2,empty())),empty())),Temp109),
    as_text(Temp109,Temp110),
    display(Temp110).
% EnkiString
display(X) :-
    writeln(X).

% FuncType (Any "T3") EnkiString
as_text(X,Temp0) :-
    term_to_atom(X,Temp0).

% FuncType (Any "T6") (Any "T6")
the(X,X).

% FuncType (Any "T8") (Any "T8")
id(X,X).

% EnkiInt
odd(X) :-
    Temp1 #= (2 * K),
    Temp2 #= (Temp1 + 1),
    X = Temp2.

% EnkiInt
even(X) :-
    Temp3 #= (2 * K),
    X = Temp3.

% FuncType EnkiInt EnkiInt
square_root(X,Root) :-
    Temp4 #= (Root ^ 2),
    Temp4 = X.

% RuleType EnkiInt EnkiInt
divides(A,B) :-
    Temp5 #= (A * N),
    B = Temp5.

% FuncType (Any "T29") (FuncType (TypeName [Named "list",Any "T29"]) (TypeName [Named "list",Any "T29"]))
prepend_to(Head,Tail,cons(Head,Tail)).

% FuncType (TypeName [Named "list",Any "T46"]) EnkiInt
length_of(List,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            List = cons(H,T)
            ->
            length_of(T,Temp6),
            Temp7 #= (1 + Temp6),
            AUTOGENERATEDFUNCTIONRESULT = Temp7
        ;
            AUTOGENERATEDFUNCTIONRESULT = 0
    ).

% FuncType (Any "T59") (FuncType (TypeName [Named "list",Any "T59"]) (TypeName [Named "list",Any "T59"]))
construct(Head,Full,Tail) :-
    Full = cons(Head,Tail).

% FuncType (TypeName [Named "list",Any "T86"]) (FuncType (TypeName [Named "list",Any "T86"]) (TypeName [Named "list",Any "T86"]))
concat_with(A,B,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            A = cons(H,T)
            ->
            concat_with(T,B,Temp8),
            prepend_to(H,Temp8,Temp9),
            AUTOGENERATEDFUNCTIONRESULT = Temp9
        ;
            AUTOGENERATEDFUNCTIONRESULT = B
    ).

% FuncType (TypeName [Named "list",TypeName [Named "list",Any "T115"]]) (TypeName [Named "list",Any "T115"])
flatten(List,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            List = cons(H,T)
            ->
            flatten(T,Temp10),
            concat_with(H,Temp10,Temp11),
            AUTOGENERATEDFUNCTIONRESULT = Temp11
        ;
            AUTOGENERATEDFUNCTIONRESULT = empty()
    ).

% FuncType (TypeName [Named "list",Any "T146"]) (FuncType (TypeName [Named "list",Any "T146"]) (TypeName [Named "list",Any "T146"]))
reverseAcc(A,Acc,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            A = cons(H,T)
            ->
            reverseAcc(T,cons(H,Acc),Temp12),
            AUTOGENERATEDFUNCTIONRESULT = Temp12
        ;
            AUTOGENERATEDFUNCTIONRESULT = Acc
    ).

% FuncType (TypeName [Named "list",Any "T155"]) (TypeName [Named "list",Any "T155"])
reverse_list(A,Temp13) :-
    reverseAcc(A,empty(),Temp13).

% FuncType (TypeName [Named "list",EnkiInt]) EnkiInt
sum_of(List,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            List = cons(H,T)
            ->
            sum_of(T,Temp14),
            Temp15 #= (H + Temp14),
            AUTOGENERATEDFUNCTIONRESULT = Temp15
        ;
            AUTOGENERATEDFUNCTIONRESULT = 0
    ).

% FuncType EnkiInt (FuncType (TypeName [Named "list",EnkiInt]) (TypeName [Named "list",Any "T198"]))
multiples_of_in(A,List,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            List = cons(H,T),
            divides(A,H)
            ->
            multiples_of_in(A,T,Temp16),
            AUTOGENERATEDFUNCTIONRESULT = cons(H,Temp16)
        ;
        (
                List = cons(H,T)
                ->
                multiples_of_in(A,T,Temp17),
                AUTOGENERATEDFUNCTIONRESULT = Temp17
            ;
                AUTOGENERATEDFUNCTIONRESULT = empty()
        )
    ).

% FuncType (TypeName [Named "list",Any "T260"]) EnkiString
formatHelper(List,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            List = cons(H,empty())
            ->
            as_text(H,Temp18),
            atom_concat(Temp18,"]",Temp19),
            AUTOGENERATEDFUNCTIONRESULT = Temp19
        ;
        (
                List = cons(H,T)
                ->
                as_text(H,Temp20),
                atom_concat(Temp20,",",Temp21),
                formatHelper(T,Temp22),
                atom_concat(Temp21,Temp22,Temp23),
                AUTOGENERATEDFUNCTIONRESULT = Temp23
            ;
                AUTOGENERATEDFUNCTIONRESULT = "]"
        )
    ).

% FuncType (TypeName [Named "list",Any "T273"]) EnkiString
format_list(List,Temp25) :-
    formatHelper(List,Temp24),
    atom_concat("[",Temp24,Temp25).

% FuncType EnkiInt (FuncType EnkiInt (TypeName [Named "list",Any "T283"]))
range_to(Low,High,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            Low #> High
            ->
            AUTOGENERATEDFUNCTIONRESULT = empty()
        ;
            Temp26 #= (Low + 1),
            range_to(Temp26,High,Temp27),
            AUTOGENERATEDFUNCTIONRESULT = cons(Low,Temp27)
    ).

% FuncType EnkiInt (FuncType EnkiInt (TypeName [Named "list",Any "T304"]))
range_from_to(Low,High,Temp28) :-
    range_to(Low,High,Temp28).

% FuncType EnkiInt (FuncType EnkiInt (TypeName [Named "list",Any "T310"]))
integers_from_to(Low,High,Temp29) :-
    range_to(Low,High,Temp29).

% FuncType (TypeName [Named "list",EnkiInt]) (TypeName [Named "list",Any "T326"])
inc(List,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            List = cons(H,T)
            ->
            Temp30 #= (H + 1),
            inc(T,Temp31),
            AUTOGENERATEDFUNCTIONRESULT = cons(Temp30,Temp31)
        ;
            AUTOGENERATEDFUNCTIONRESULT = empty()
    ).

% FuncType (TypeName [Named "list",Any "T382"]) (FuncType (TypeName [Named "list",Any "T383"]) (TypeName [Named "list",Any "T364"]))
zip_and(A,B,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            A = cons(HA,TA),
            B = cons(HB,TB)
            ->
            zip_and(TA,TB,Temp32),
            AUTOGENERATEDFUNCTIONRESULT = cons(pair_and(HA,HB),Temp32)
        ;
            AUTOGENERATEDFUNCTIONRESULT = empty()
    ).

% FuncType EnkiInt (FuncType EnkiInt EnkiInt)
max_of_and(A,B,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            A #> B
            ->
            AUTOGENERATEDFUNCTIONRESULT = A
        ;
            AUTOGENERATEDFUNCTIONRESULT = B
    ).

% FuncType EnkiInt (FuncType EnkiInt EnkiInt)
min_of_and(A,B,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            A #> B
            ->
            AUTOGENERATEDFUNCTIONRESULT = A
        ;
            AUTOGENERATEDFUNCTIONRESULT = B
    ).

% FuncType (TypeName [Named "list",EnkiInt]) EnkiInt
maximum_of(List,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            List = cons(H,empty())
            ->
            AUTOGENERATEDFUNCTIONRESULT = H
        ;
        (
                List = cons(H,T)
                ->
                maximum_of(T,Temp33),
                max_of_and(H,Temp33,Temp34),
                AUTOGENERATEDFUNCTIONRESULT = Temp34
            ;
                AUTOGENERATEDFUNCTIONRESULT = 0
        )
    ).

% FuncType (TypeName [Named "list",EnkiInt]) EnkiInt
minimum_of(List,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            List = cons(H,empty())
            ->
            AUTOGENERATEDFUNCTIONRESULT = H
        ;
        (
                List = cons(H,T)
                ->
                minimum_of(T,Temp35),
                min_of_and(H,Temp35,Temp36),
                AUTOGENERATEDFUNCTIONRESULT = Temp36
            ;
                AUTOGENERATEDFUNCTIONRESULT = 0
        )
    ).

% FuncType EnkiInt (FuncType EnkiInt EnkiInt)
find_factor_of_starting_with(N,X,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            divides(X,N)
            ->
            AUTOGENERATEDFUNCTIONRESULT = X
        ;
            Temp37 #= (X + 1),
            find_factor_of_starting_with(N,Temp37,Temp38),
            AUTOGENERATEDFUNCTIONRESULT = Temp38
    ).

% FuncType EnkiInt (TypeName [Named "list",Any "T511"])
factors_of(N,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            N = 1
            ->
            AUTOGENERATEDFUNCTIONRESULT = empty()
        ;
            find_factor_of_starting_with(N,2,Temp39),
            Factor = Temp39,
            Temp40 #= (N div Factor),
            factors_of(Temp40,Temp41),
            AUTOGENERATEDFUNCTIONRESULT = cons(Factor,Temp41)
    ).

% FuncType EnkiInt (TypeName [Named "list",Any "T541"])
digits_of(N,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            N #< 10
            ->
            AUTOGENERATEDFUNCTIONRESULT = cons(N,empty())
        ;
            Temp42 #= (10 * Rest),
            Temp43 #= (Temp42 + Digit),
            N = Temp43,
            Digit #>= 0,
            Digit #< 10,
            digits_of(Rest,Temp44),
            AUTOGENERATEDFUNCTIONRESULT = cons(Digit,Temp44)
    ).

% TypeName [Named "list",Any "T569"]
palindrome(List) :-
    reverse_list(List,Temp45),
    Temp45 = List.

% EnkiInt
palindromic_number(N) :-
    digits_of(N,Temp46),
    palindrome(Temp46).

% FuncType (Any "T606") (FuncType (TypeName [Named "list",Any "T607"]) (TypeName [Named "list",Any "T588"]))
pair_with_each(X,List,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            List = cons(H,T)
            ->
            pair_with_each(X,T,Temp47),
            AUTOGENERATEDFUNCTIONRESULT = cons(pair_and(X,H),Temp47)
        ;
            AUTOGENERATEDFUNCTIONRESULT = empty()
    ).

% FuncType (TypeName [Named "list",Any "T650"]) (FuncType (TypeName [Named "list",Any "T651"]) (TypeName [Named "list",Any "T630"]))
cartesian_product_of_and(A,B,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            A = cons(H,T)
            ->
            pair_with_each(H,B,Temp48),
            cartesian_product_of_and(T,B,Temp49),
            concat_with(Temp48,Temp49,Temp50),
            AUTOGENERATEDFUNCTIONRESULT = Temp50
        ;
            AUTOGENERATEDFUNCTIONRESULT = empty()
    ).

% FuncType (TypeName [Named "list",Any "T663"]) (FuncType (TypeName [Named "list",Any "T664"]) (TypeName [Named "list",Any "T665"]))
pairs_of_and(A,B,Temp51) :-
    cartesian_product_of_and(A,B,Temp51).

% FuncType EnkiInt (FuncType (TypeName [Named "list",Any "T692"]) (TypeName [Named "list",Any "T692"]))
take_from(N,List,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            N #> 0,
            List = cons(H,T)
            ->
            Temp52 #= (N - 1),
            take_from(Temp52,T,Temp53),
            AUTOGENERATEDFUNCTIONRESULT = cons(H,Temp53)
        ;
            AUTOGENERATEDFUNCTIONRESULT = empty()
    ).

% FuncType EnkiInt (FuncType (TypeName [Named "list",Any "T718"]) (TypeName [Named "list",Any "T718"]))
drop_from(N,List,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            N #> 0,
            List = cons(H,T)
            ->
            Temp54 #= (N - 1),
            drop_from(Temp54,T,Temp55),
            AUTOGENERATEDFUNCTIONRESULT = Temp55
        ;
            AUTOGENERATEDFUNCTIONRESULT = List
    ).

% FuncType (TypeName [Named "list",EnkiInt]) EnkiInt
product_of(List,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            List = cons(H,T)
            ->
            product_of(T,Temp56),
            Temp57 #= (H * Temp56),
            AUTOGENERATEDFUNCTIONRESULT = Temp57
        ;
            AUTOGENERATEDFUNCTIONRESULT = 1
    ).

% FuncType EnkiInt (FuncType (TypeName [Named "list",Any "T768"]) (FuncType (Any "T776") (Any "T776")))
element_of_starting_with(N,List,H,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            N #=< 0
            ->
            AUTOGENERATEDFUNCTIONRESULT = H
        ;
        (
                List = cons(X,Rest)
                ->
                Temp58 #= (N - 1),
                element_of_starting_with(Temp58,Rest,X,Temp59),
                AUTOGENERATEDFUNCTIONRESULT = Temp59
            ;
                AUTOGENERATEDFUNCTIONRESULT = H
        )
    ).

% FuncType EnkiInt (FuncType (TypeName [Named "list",Any "T821"]) (TypeName [Named "list",Any "T789"]))
chunks_of_size_in(L,List,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            List = empty()
            ->
            AUTOGENERATEDFUNCTIONRESULT = empty()
        ;
            take_from(L,List,Temp60),
            drop_from(L,List,Temp61),
            chunks_of_size_in(L,Temp61,Temp62),
            AUTOGENERATEDFUNCTIONRESULT = cons(Temp60,Temp62)
    ).

% FuncType EnkiInt (FuncType (TypeName [Named "list",Any "T828"]) (TypeName [Named "list",Any "T829"]))
chunks_of_length_in(L,List,Temp63) :-
    chunks_of_size_in(L,List,Temp63).

% RuleType (TypeName [Named "list",Any "T842"]) (Any "T842")
contains(List,Element) :-
    (
            List = cons(H,T),
            H = Element
            ->
            1 = 1
        ;
        (
                List = cons(H,T)
                ->
                contains(T,Element)
            ;
                1 = 2
        )
    ).

% FuncType (Any "T876") (FuncType (TypeName [Named "list",Any "T877"]) (TypeName [Named "list",Any "T877"]))
remove_from(Element,List,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            List = cons(H,T),
            H = Element
            ->
            AUTOGENERATEDFUNCTIONRESULT = T
        ;
        (
                List = cons(H,T)
                ->
                remove_from(Element,T,Temp64),
                AUTOGENERATEDFUNCTIONRESULT = cons(H,Temp64)
            ;
                1 = 2,
                AUTOGENERATEDFUNCTIONRESULT = empty()
        )
    ).

% FuncType (Any "T891") (FuncType (Any "T892") (TypeName [Named "mapping",Any "T891",Any "T892"]))
maps_to(X,Y,pipe_dash_gt_(X,Y)).

% FuncType EnkiInt (FuncType EnkiInt (TypeName [Named "ordering"]))
compare_to(A,B,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            A #> B
            ->
            AUTOGENERATEDFUNCTIONRESULT = greater()
        ;
        (
                A #< B
                ->
                AUTOGENERATEDFUNCTIONRESULT = less()
            ;
                AUTOGENERATEDFUNCTIONRESULT = equal()
        )
    ).

% FuncType (TypeName [Named "mapping",Any "T914",Any "T915"]) (Any "T914")
key_in(AUTOGENARG3,K) :-
    maps_to(K,V,Temp65),
    AUTOGENARG3 = Temp65.

% FuncType (TypeName [Named "mapping",Any "T925",Any "T926"]) (Any "T926")
value_in(AUTOGENARG3,V) :-
    maps_to(K,V,Temp66),
    AUTOGENARG3 = Temp66.

% FuncType (TypeName [Named "mapping",EnkiInt,Any "T938"]) (FuncType (TypeName [Named "mapping",EnkiInt,Any "T947"]) (TypeName [Named "ordering"]))
compare_keys_to(AUTOGENARG3,AUTOGENARG5,Temp67) :-
    AUTOGENARG3 = pipe_dash_gt_(K1,V1),
    AUTOGENARG5 = pipe_dash_gt_(K2,V2),
    compare_to(K1,K2,Temp67).

% FuncType (TypeName [Named "mapping",Any "T960",EnkiInt]) (FuncType (TypeName [Named "mapping",Any "T969",EnkiInt]) (TypeName [Named "ordering"]))
compare_values_to(AUTOGENARG3,AUTOGENARG5,Temp68) :-
    AUTOGENARG3 = pipe_dash_gt_(K1,V1),
    AUTOGENARG5 = pipe_dash_gt_(K2,V2),
    compare_to(V1,V2,Temp68).

% FuncType (Any "T989") (FuncType (TypeName [Named "list",Any "T981"]) (Any "T990"))
get_key_from(Key,Map,V) :-
    contains(Map,pipe_dash_gt_(Key,V)).

% FuncType (Any "T1006") (FuncType (Any "T1007") (FuncType (TypeName [Named "list",Any "T998"]) (TypeName [Named "list",Any "T998"])))
insert_into(K,V,Map,cons(pipe_dash_gt_(K,V),Map)).

% FuncType (Any "T1024") (FuncType (TypeName [Named "list",Any "T1015"]) (TypeName [Named "list",Any "T1015"]))
remove_key_from(Key,Map,Temp69) :-
    remove_from(pipe_dash_gt_(Key,V),Map,Temp69).

% FuncType (Any "T1062") (FuncType (TypeName [Named "list",Any "T1054"]) (TypeName [Named "list",Any "T1054"]))
increment_key_in(Key,Map,Temp72) :-
    Temp71 #= (V + 1),
    remove_from(pipe_dash_gt_(Key,V),Map,Temp70),
    insert_into(Key,Temp71,Temp70,Temp72).

% FuncType (TypeName [Named "mapping",EnkiInt,Any "T1105"]) (FuncType (TypeName [Named "list",TypeName [Named "mapping",EnkiInt,Any "T1106"]]) (TypeName [Named "mapping",EnkiInt,Any "T1105"]))
max_key_at_least_in(M1,Map,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            Map = cons(M2,Assocs),
            compare_keys_to(M2,M1,Temp73),
            Temp73 = less()
            ->
            max_key_at_least_in(M2,Assocs,Temp74),
            AUTOGENERATEDFUNCTIONRESULT = Temp74
        ;
        (
                Map = cons(P,Assocs)
                ->
                max_key_at_least_in(M1,Assocs,Temp75),
                AUTOGENERATEDFUNCTIONRESULT = Temp75
            ;
                AUTOGENERATEDFUNCTIONRESULT = M1
        )
    ).

% FuncType (TypeName [Named "list",TypeName [Named "mapping",EnkiInt,Any "T1135"]]) (TypeName [Named "maybe",TypeName [Named "mapping",EnkiInt,Any "T1135"]])
max_key_in(Map,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            Map = cons(M1,Assocs)
            ->
            max_key_at_least_in(M1,Map,Temp76),
            AUTOGENERATEDFUNCTIONRESULT = just(Temp76)
        ;
            AUTOGENERATEDFUNCTIONRESULT = nothing()
    ).

% FuncType (TypeName [Named "mapping",EnkiInt,Any "T1180"]) (FuncType (TypeName [Named "list",TypeName [Named "mapping",EnkiInt,Any "T1181"]]) (TypeName [Named "mapping",EnkiInt,Any "T1180"]))
min_key_no_more_than_in(M1,Map,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            Map = cons(M2,Assocs),
            compare_keys_to(M2,M1,Temp77),
            Temp77 = less()
            ->
            min_key_no_more_than_in(M2,Assocs,Temp78),
            AUTOGENERATEDFUNCTIONRESULT = Temp78
        ;
        (
                Map = cons(P,Assocs)
                ->
                min_key_no_more_than_in(M1,Assocs,Temp79),
                AUTOGENERATEDFUNCTIONRESULT = Temp79
            ;
                AUTOGENERATEDFUNCTIONRESULT = M1
        )
    ).

% FuncType (TypeName [Named "list",TypeName [Named "mapping",EnkiInt,Any "T1210"]]) (TypeName [Named "maybe",TypeName [Named "mapping",EnkiInt,Any "T1210"]])
min_key_in(Map,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            Map = cons(M1,Assocs)
            ->
            min_key_no_more_than_in(M1,Map,Temp80),
            AUTOGENERATEDFUNCTIONRESULT = just(Temp80)
        ;
            AUTOGENERATEDFUNCTIONRESULT = nothing()
    ).

% FuncType (TypeName [Named "mapping",Any "T1255",EnkiInt]) (FuncType (TypeName [Named "list",TypeName [Named "mapping",Any "T1256",EnkiInt]]) (TypeName [Named "mapping",Any "T1255",EnkiInt]))
max_value_at_least_in(M1,Map,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            Map = cons(M2,Assocs),
            compare_values_to(M2,M1,Temp81),
            Temp81 = less()
            ->
            max_value_at_least_in(M2,Assocs,Temp82),
            AUTOGENERATEDFUNCTIONRESULT = Temp82
        ;
        (
                Map = cons(P,Assocs)
                ->
                max_value_at_least_in(M1,Assocs,Temp83),
                AUTOGENERATEDFUNCTIONRESULT = Temp83
            ;
                AUTOGENERATEDFUNCTIONRESULT = M1
        )
    ).

% FuncType (TypeName [Named "list",TypeName [Named "mapping",Any "T1285",EnkiInt]]) (TypeName [Named "maybe",TypeName [Named "mapping",Any "T1285",EnkiInt]])
max_value_in(Map,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            Map = cons(M1,Assocs)
            ->
            max_value_at_least_in(M1,Map,Temp84),
            AUTOGENERATEDFUNCTIONRESULT = just(Temp84)
        ;
            AUTOGENERATEDFUNCTIONRESULT = nothing()
    ).

% FuncType (TypeName [Named "mapping",Any "T1330",EnkiInt]) (FuncType (TypeName [Named "list",TypeName [Named "mapping",Any "T1331",EnkiInt]]) (TypeName [Named "mapping",Any "T1330",EnkiInt]))
min_value_no_more_than_in(M1,Map,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            Map = cons(M2,Assocs),
            compare_values_to(M2,M1,Temp85),
            Temp85 = less()
            ->
            min_value_no_more_than_in(M2,Assocs,Temp86),
            AUTOGENERATEDFUNCTIONRESULT = Temp86
        ;
        (
                Map = cons(P,Assocs)
                ->
                min_value_no_more_than_in(M1,Assocs,Temp87),
                AUTOGENERATEDFUNCTIONRESULT = Temp87
            ;
                AUTOGENERATEDFUNCTIONRESULT = M1
        )
    ).

% FuncType (TypeName [Named "list",TypeName [Named "mapping",Any "T1360",EnkiInt]]) (TypeName [Named "maybe",TypeName [Named "mapping",Any "T1360",EnkiInt]])
min_value_in(Map,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            Map = cons(M1,Assocs)
            ->
            min_value_no_more_than_in(M1,Map,Temp88),
            AUTOGENERATEDFUNCTIONRESULT = just(Temp88)
        ;
            AUTOGENERATEDFUNCTIONRESULT = nothing()
    ).

% FuncType (TypeName [Named "list",EnkiInt]) (FuncType (TypeName [Named "list",EnkiInt]) EnkiInt)
first_vote_for_in(Candidates,Votes,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            Votes = cons(Vote,Rest),
            contains(Candidates,Vote)
            ->
            AUTOGENERATEDFUNCTIONRESULT = Vote
        ;
        (
                Votes = cons(Vote,Rest)
                ->
                first_vote_for_in(Candidates,Rest,Temp89),
                AUTOGENERATEDFUNCTIONRESULT = Temp89
            ;
                AUTOGENERATEDFUNCTIONRESULT = 1
        )
    ).

% FuncType (TypeName [Named "list",EnkiInt]) (FuncType (TypeName [Named "list",TypeName [Named "list",EnkiInt]]) (TypeName [Named "list",Any "T1424"]))
tally_votes_for_in(Candidates,Ballots,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            Ballots = cons(Ballot,Rest)
            ->
            first_vote_for_in(Candidates,Ballot,Temp90),
            Candidate = Temp90,
            tally_votes_for_in(Candidates,Rest,Temp91),
            increment_key_in(Candidate,Temp91,Temp92),
            AUTOGENERATEDFUNCTIONRESULT = Temp92
        ;
            AUTOGENERATEDFUNCTIONRESULT = empty()
    ).

% FuncType (TypeName [Named "list",EnkiInt]) (FuncType (TypeName [Named "list",TypeName [Named "list",EnkiInt]]) (TypeName [Named "maybe",TypeName [Named "mapping",Any "T1517",EnkiInt]]))
run_voting_for_using(Candidates,Ballots,AUTOGENERATEDFUNCTIONRESULT) :-
    (
            tally_votes_for_in(Candidates,Ballots,Temp93),
            Tally = Temp93,
            max_value_in(Tally,Temp94),
            Best = Temp94,
            maps_to(Winner,Votes,Temp95),
            just(Temp95) = Best,
            length_of(Ballots,Temp96),
            Temp97 #= (Temp96 div 2),
            Votes #> Temp97
            ->
            AUTOGENERATEDFUNCTIONRESULT = Best
        ;
            tally_votes_for_in(Candidates,Ballots,Temp98),
            Tally = Temp98,
            min_value_in(Tally,Temp99),
            just(pipe_dash_gt_(Candidate,Votes)) = Temp99,
            remove_from(Candidate,Candidates,Temp100),
            run_voting_for_using(Temp100,Ballots,Temp101),
            AUTOGENERATEDFUNCTIONRESULT = Temp101
    ).