mod UTILITY is
    protecting STRING .
    protecting LIST{String} .

    vars S S1 S2 Sep : String .
    var Strs : List{String} .

    op intercalate : String List{String} -> String .
    eq intercalate(Sep, nil)        = "" .
    eq intercalate(Sep, S1)         = S1 .
    eq intercalate(Sep, S1 S2 Strs) = S1 + Sep + intercalate(Sep, S2 Strs) .

    op isEmpty : List{String} -> Bool .
    eq isEmpty(nil)    = true .
    eq isEmpty(S Strs) = false .
endm

